apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-zoo
spec:
  storageClassName: "mystcls"
  capacity:
    storage: STORAGE_SIZE_ZOO
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: PV_CLAIM_NAME_ZOO
  gcePersistentDisk:
    pdName: PD_NAME_ZOO
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PV_CLAIM_NAME_ZOO
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE_SIZE
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-brokers-0
spec:
  storageClassName: "mystcls"
  capacity:
    storage: STORAGE_SIZE_BROKER_0
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: PV_CLAIM_NAME_BROKER_0
  gcePersistentDisk:
    pdName: PD_NAME_BROKER_0
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PV_CLAIM_NAME_BROKER_0
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE_SIZE_BROKER_0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-brokers-1
spec:
  storageClassName: "mystcls"
  capacity:
    storage: STORAGE_SIZE_BROKER_1
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: PV_CLAIM_NAME_BROKER_1
  gcePersistentDisk:
    pdName: PD_NAME_BROKER_1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PV_CLAIM_NAME_BROKER_1
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE_SIZE_BROKER_1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-brokers-2
spec:
  storageClassName: "mystcls"
  capacity:
    storage: STORAGE_SIZE_BROKER_2
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: PV_CLAIM_NAME_BROKER_2
  gcePersistentDisk:
    pdName: PD_NAME_BROKER_2
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PV_CLAIM_NAME_BROKER_2
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE_SIZE_BROKER_2
